global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gvpb_identity_api'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['gvpb.identity.api:443']
    tls_config:
      insecure_skip_verify: true