version: '3.4'

services:
  gvpb.identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "5031:443"
    env_file:
      - env/Commons.env
      - env/Databases.env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - gvpb-identity
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  gvpb.identity.db:
    image: postgres:latest
    restart: always
    ports:
      - 5548:5432
    networks:
      - gvpb-identity
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  gvpb.identity.web:
    env_file:
      - env/Commons.env
      - env/Databases.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    networks:
      - gvpb-identity
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  influxdb:
    image: influxdb:1.8
    restart: always
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: k6
      INFLUXDB_USER_PASSWORD: k6
    networks:
      - gvpb-identity
    volumes:
      - influxdb-data:/var/lib/influxdb
 
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - gvpb-identity
    depends_on:
      - gvpb.identity.api


  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    networks:
      - gvpb-identity
    depends_on:
      - influxdb

networks:
  gvpb-identity:

volumes:
  postgres-data:
  influxdb-data:
  prometheus-data:


